///// MAPEAR DISPACHT

export const LIST_MACHINE = 'LIST_MACHINE'
export const CHARGE_MACHINE = 'CHARGE_MACHINE'
export const USE_MACHINE = 'USE_MACHINE'



//// LOGIN

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const USER_SUCCESS = 'USER_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'